{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "anvil.fullname" . }}-server
  labels:
    {{- include "anvil.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.server.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.server.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.server.ingress.path }}
            pathType: {{ .Values.server.ingress.pathType }}
            backend:
              service:
                name: {{ include "anvil.fullname" . }}-server
                port:
                  number: {{ .Values.server.service.port }}
{{- end }}
