{{- if and .Values.redis.deploy .Values.redis.password (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anvil.redisSecretName" . }}
  labels:
    {{- include "anvil.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
{{- end }}
