// Webhook ingress throughput + latency percentiles for Anvil.
// Exercises the REAL SDK path (verify -> idempotency key -> dedupe enqueue)
// against an in-memory queue mock — no Redis, no worker. Run:
//   node bench/throughput.mjs
// Tunables: BENCH_DURATION (s), BENCH_CONNECTIONS, BENCH_UNIQUE (distinct bodies)
import { createServer as createHttp } from 'node:http'
import { createHmac } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import autocannon from 'autocannon'
import { verify } from '../packages/sdk/dist/internal/verify.js'
import { computeIdempotencyKey } from '../packages/sdk/dist/internal/idempotency.js'
import { enqueueWebhook } from '../packages/sdk/dist/internal/enqueue.js'

const here = dirname(fileURLToPath(import.meta.url))
const SECRET = 'whsec_' + 'a'.repeat(32)
const HEADER = 'x-signature'
const DURATION = Number(process.env.BENCH_DURATION ?? 10)
const CONNECTIONS = Number(process.env.BENCH_CONNECTIONS ?? 50)
const UNIQUE = Number(process.env.BENCH_UNIQUE ?? 200)

// In-memory stand-in for a BullMQ Queue. enqueueWebhook only calls getJob/add,
// and a duplicate jobId is a no-op add — that is Anvil's dedupe contract.
function mockQueue() {
  const jobs = new Map()
  return {
    async getJob(id) {
      return jobs.get(id)
    },
    async add(name, data, opts) {
      const id = opts.jobId
      const existing = jobs.get(id)
      if (existing) return existing
      const job = { id, name, data }
      jobs.set(id, job)
      return job
    },
  }
}

const queue = mockQueue()
const counters = { total: 0, accepted: 0, replayed: 0, rejected: 0 }

// Same request handling as createServer(), minus the BullMQ/Redis wiring.
const server = createHttp((req, res) => {
  if (req.method !== 'POST' || req.url !== '/webhooks') {
    res.statusCode = 404
    return res.end()
  }
  const chunks = []
  req.on('data', (c) => chunks.push(c))
  req.on('end', async () => {
    counters.total++
    const raw = Buffer.concat(chunks)
    const sig = req.headers[HEADER] ?? ''
    if (!verify(raw, sig, SECRET)) {
      counters.rejected++
      res.statusCode = 401
      return res.end('{"error":"invalid signature"}')
    }
    const key = computeIdempotencyKey(sig, raw)
    const result = await enqueueWebhook(queue, key, { body: raw.toString('utf8'), sig })
    if (result.replayed) counters.replayed++
    else counters.accepted++
    res.statusCode = 202
    res.setHeader('content-type', 'application/json')
    res.end(JSON.stringify(result))
  })
})

const sign = (body) => 'sha256=' + createHmac('sha256', SECRET).update(body).digest('hex')

// UNIQUE valid payloads + a ~5% tampered slice (valid sig over a different
// body) to exercise the 401 reject path. autocannon cycles this array, so
// repeats of a valid body collapse to one queued job (dedupe -> replayed).
function buildRequests() {
  const reqs = []
  for (let i = 0; i < UNIQUE; i++) {
    const body = JSON.stringify({
      id: `evt_${i}`,
      type: 'payment.succeeded',
      created: 1700000000 + i,
      data: { object: { amount: 4200 + i, currency: 'usd' } },
    })
    reqs.push({
      method: 'POST',
      path: '/webhooks',
      headers: { [HEADER]: sign(body), 'content-type': 'application/json' },
      body,
    })
    if (i % 20 === 0) {
      reqs.push({
        method: 'POST',
        path: '/webhooks',
        headers: { [HEADER]: sign('unrelated'), 'content-type': 'application/json' },
        body,
      })
    }
  }
  return reqs
}

const pct = (n, d) => (d ? Number(((n / d) * 100).toFixed(1)) : 0)

await new Promise((resolve) => server.listen(0, resolve))
const { port } = server.address()

const result = await autocannon({
  url: `http://127.0.0.1:${port}`,
  connections: CONNECTIONS,
  duration: DURATION,
  requests: buildRequests(),
})

server.close()

const L = result.latency
const summary = {
  node: process.version,
  duration_s: DURATION,
  connections: CONNECTIONS,
  unique_payloads: UNIQUE,
  throughput_rps: Math.round(result.requests.average),
  latency_ms: { p50: L.p50, p90: L.p90, p97_5: L.p97_5, p99: L.p99, p99_9: L.p99_9, max: L.max },
  requests_total: counters.total,
  accepted_202: counters.accepted,
  replayed_dedupe: counters.replayed,
  rejected_401: counters.rejected,
  non2xx: result.non2xx,
  dedupe_rate_pct: pct(counters.replayed, counters.total),
  reject_rate_pct: pct(counters.rejected, counters.total),
  // Worker-side outcomes — an ingress bench runs no worker, so not measured.
  retry_rate_pct: null,
  dead_letter_rate_pct: null,
}

const md = `# Anvil webhook ingress — throughput report

Generated by \`node bench/throughput.mjs\`. In-memory queue mock, no Redis;
exercises the real verify -> idempotency -> dedupe-enqueue path.

| Metric | Value |
|---|---|
| Throughput | ${summary.throughput_rps} req/s |
| p50 latency | ${L.p50} ms |
| p90 latency | ${L.p90} ms |
| p97.5 latency | ${L.p97_5} ms |
| p99 latency | ${L.p99} ms |
| p99.9 latency | ${L.p99_9} ms |
| Requests | ${counters.total} over ${DURATION}s @ ${CONNECTIONS} conns |
| Accepted (202) | ${counters.accepted} |
| Deduped (replayed) | ${counters.replayed} (${summary.dedupe_rate_pct}%) |
| Rejected (401) | ${counters.rejected} (${summary.reject_rate_pct}%) |
| Retry rate | n/a (worker-side) |
| Dead-letter rate | n/a (worker-side) |
| Node | ${process.version} |

Retry and dead-letter rates are worker-side outcomes; an ingress throughput
bench runs no worker, so they are reported as n/a rather than fabricated.
`

writeFileSync(join(here, 'report-latest.json'), JSON.stringify(summary, null, 2) + '\n')
writeFileSync(join(here, 'report-latest.md'), md)
process.stdout.write(md + '\n')
